### ISSUE TITLE
'Connection' Widget

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/mush#9]
Need a 'Connection' widget that represents an edge in the graph

Rough Feature Ideas:
- [x] Draws some kind of line (straight line or bezier curve)
- [ ] Highlights on mouse over, selects on click - allow 'users' to register an 'on_select' callback, could be used to update some kind of other 'PropertyGrid' widget with the edge/connections properties when a connection is selected.
- [ ] Delete with delete key when selected - probably implemented as some kind of 'on_delete' callback?

**Comment by bvssvni** [comment]
Callbacks can be replaced by returning an enum with the actions the user performs, since one is likely to send all output events to the same receiver, or one can use just one callback receiving the enum as argument. Keeping events together is a nice way of making the high level code more understandable.

**Comment by viperscape** [comment]
I'll probably reference this issue later in a future post, closing for now
